apiVersion: apps/v1
kind: Deployment
metadata:
  name: ag-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ag-service
  template:
    metadata:
      labels:
        app: ag-service
    spec:
      containers:
        - name: ag-service
          image: nilakshanr/ag-service:0.0.2
          ports:
            - containerPort: 8080
